version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test-backend:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test backend
          command: |
            cd backend
            go get -v -t -d ./...
            go test -cover -v ./...

  build-backend:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build backend docker image
          environment:
            IMAGE: todo-backend
          command: |
            cd backend
            docker build -t "$DOCKERHUB_USERNAME"/"$IMAGE":latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/"$IMAGE":latest

workflows:
  version: 2
  test_build_master:
    jobs:
      - test-backend:
          filters:
            branches:
              only: master
      - build-backend:
          requires:
            - test-backend
          filters:
            branches:
              only: master