version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-backend:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          environment:
            IMAGE: todo-backend
          command: |
            cd backend
            docker build -t "$DOCKERHUB_USERNAME"/"$IMAGE":latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/"$IMAGE":latest

workflows:
  version: 2
  build_master:
    jobs:
      - build-backend:
          filters:
            branches:
              only: master